// <auto-generated />
using System;
using MediaControlApp.Infrastructure.DataAccess.MediaStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaControlApp.Infrastructure.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    partial class MediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("MediaControlApp.Domain.Models.Media.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("MediaControlApp.Domain.Models.Media.Ganre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MediaTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaTypeId");

                    b.ToTable("Ganres");
                });

            modelBuilder.Entity("MediaControlApp.Domain.Models.Media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GanreId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastConsumedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublisedDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GanreId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("MediaControlApp.Domain.Models.Media.MediaType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaTypes");
                });

            modelBuilder.Entity("MediaControlApp.Domain.Models.Media.Ganre", b =>
                {
                    b.HasOne("MediaControlApp.Domain.Models.Media.MediaType", "MediaType")
                        .WithMany("Ganres")
                        .HasForeignKey("MediaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaType");
                });

            modelBuilder.Entity("MediaControlApp.Domain.Models.Media.Media", b =>
                {
                    b.HasOne("MediaControlApp.Domain.Models.Media.Author", "Author")
                        .WithMany("Medias")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediaControlApp.Domain.Models.Media.Ganre", "Ganre")
                        .WithMany("Medias")
                        .HasForeignKey("GanreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MediaControlApp.Domain.Models.Media.ValueObjects.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("MediaId")
                                .HasColumnType("TEXT");

                            b1.Property<double>("Value")
                                .HasColumnType("REAL");

                            b1.HasKey("MediaId");

                            b1.ToTable("Medias");

                            b1.WithOwner()
                                .HasForeignKey("MediaId");
                        });

                    b.Navigation("Author");

                    b.Navigation("Ganre");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("MediaControlApp.Domain.Models.Media.Author", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("MediaControlApp.Domain.Models.Media.Ganre", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("MediaControlApp.Domain.Models.Media.MediaType", b =>
                {
                    b.Navigation("Ganres");
                });
#pragma warning restore 612, 618
        }
    }
}
